server:
  port: 9012
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ryan1234
    url: jdbc:mysql://localhost:3307/bank
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
bank:
  currency: USD