server:
  port: 9012
db:
  user: root
  password: ryan1234
  host: localhost
  port: 3307
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}
    url: jdbc:mysql://${db.host}:${db.port}/bank
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
bank:
  currency: USD
  withdraw:
    limit: 800